### PR TITLE
add api workflow

### PR DESCRIPTION
**Pull request by stevenhua0320**
Add api workflow

### CODE REVIEW

**Comment by bobleesj** [comment]
Are these generated dynamically by the cookiecutter? It doesn't look like it. It's probably best to have a single PR that both removes older docs and handle generated API so that we don't have to have additional PRs related to docs.

Also recommend to git add all the older github workflows and only have the new ones: This should have been done in a single PR as well.

Screenshot 2024-09-27 at 11 55 29 AM

**Comment by stevenhua0320** [comment]
screenshot of new api page
Screenshot 2024-09-27 at 12 52 04 PM

**Comment by bobleesj** [comment]
@stevenhua0320 good, now can you follow the API workflow instruction to generate .rst files and render them? There should be a new section called "Package API" Ex) https://github.com/Billingegroup/bg-mpl-stylesheets/pull/66

**Comment by bobleesj** [comment]
Screenshot 2024-09-27 at 12 56 20 PM

.rst files have been removed - please double check the "Files Changed"

**Comment by stevenhua0320** [comment]
> Screenshot 2024-09-27 at 12 56 20 PM
> .rst files have been removed - please double check the "Files Changed"

Yeah, I removed them right now since it is generated by the old cookiecutter.

**Comment by stevenhua0320** [comment]
updated api workflow build
Screenshot 2024-09-27 at 1 06 39 PM
Screenshot 2024-09-27 at 1 06 31 PM

**Comment by bobleesj** [comment]
The file `extending.rst` is not being rendered here in the screenshot?

**Comment by stevenhua0320** [comment]
@bobleesj 
Screenshot 2024-09-27 at 1 28 52 PM
Here is the extending srmise page

**Comment by stevenhua0320** [comment]
I've put `extending.rst` under the source dir but I did not see it is on nav. 
Screenshot 2024-09-27 at 2 36 29 PM

**Comment by bobleesj** [comment]
I also see lots of useful content under `tutorials` let's add those too

**Comment by sbillinge** [comment]
@bobleesj thanks for the help with this ,🙏

**Comment by sbillinge** [comment]
Polese let me know when it is ready to merge

**Comment by stevenhua0320** [comment]
Hi Simon @sbillinge, right now the functionality of loading `extending.rst` and `tutorial.rst` to the nav on the index page might not be possible right now. But these ones could be searched when typing the keywords. I have made an issue for that. So, we should merge these first.

**Comment by sbillinge** [comment]
ok, understood.  Thanks @stevenhua0320

**Pull request merged**
