### PR TITLE
Support Python 3.13, drop 3.10

### LINKED ISSUE #144: Add requires-python = ">=3.11, <=3.13" in pyproject.toml
Please refer to https://github.com/diffpy/diffpy.srmise/pull/143 for the changes in pyproject.toml

### PR DESCRIPTION
**Pull request by bobleesj**
**PLEASE READ FOR GITHUB MAINTAINERS:**

If your package supports Python 3.10, 3.11, 3.12:
- add `requires-python = ">=3.10, <3.13"`

If your package supports Python 3.11, 3.12, 3.13:
- add `requires-python = ">=3.11, <3.14"`

---

**For this PR reviewer:**

Closes #144 

```
conda create -n diffpy.srmise_env python=3.13
conda install --file requirements/conda.txt --file requirements/test.txt
pip install -e . --no-deps
```

Testing result:

Screenshot 2024-10-24 at 2 41 23 PM

No changes were needed.

### CODE REVIEW

**Comment by bobleesj** [comment]
@sbillinge ready for review

**Review by sbillinge — COMMENTED** [review]
Talking to Tieqiong, we realize that in the toml file we want the line `requires-python = ">=3.10"` to be changed to 3.11 but also a `<=3.13` (not sure the right syntax).  In the future when conda-forge migrates to the next python version this will then fail with an unresolved error and not just break in the code.

This  applies to all the packages so we need to let everyone know and have them update their packages this way.

**Review by bobleesj — COMMENTED** [review]
@sbillinge ready for review - `requires-python = ">=3.11, <=3.13"` added

**Comment by bobleesj** [comment]
@sbillinge Added an news item for `requires-python = ">=3.11, <=3.13"`, ready for review

**Comment by bobleesj** [comment]
@sbillinge Okay - `>=3.11, <3.14` added. Just need to fix the issue titles

**Comment by bobleesj** [comment]
@sbillinge  Updated the news file as provided in the `general` group channel. Ready for review

**Pull request merged**
