### PR TITLE
changes generated by cookiecutter in doc files

### PR DESCRIPTION
**Pull request by stevenhua0320**

### CODE REVIEW

**Comment by bobleesj** [comment]
these will be populated again during the API workflow?

**Comment by stevenhua0320** [comment]
> these will be populated again during the API workflow?

I think so, because I haven't done the API workflow yet, so there must be a change when API workflow is done.

**Comment by sbillinge** [comment]
@stevenhua0320 please make an issue to check that these are repopulated after the API workflow. Then I can merge this.

**Comment by stevenhua0320** [comment]
I think we can close this since it is addressed by PR #124

**Pull request closed without merging**
